export const accounts = [
  {
    "id": 1,
    "email": "etessyman0@tinypic.com",
    "password": "xS7+_4Q2",
    "role": "USER",
    "full_name": "Halli Nemchinov",
    "gender": 1,
    "phone_number": "4212424100",
    "address": "8 Morrow Parkway",
    "created_date": "10/16/2023",
    "created_by": "Percy Clemanceau",
    "updated_date": "3/29/2024",
    "updated_by": "Eveline Tessyman",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 2,
    "email": "vhanselmann1@51.la",
    "password": "qG2\u003Cv+Q|U(+|C",
    "role": "USER",
    "full_name": "Candida Enric",
    "gender": 0,
    "phone_number": "5337723329",
    "address": "12 Monterey Way",
    "created_date": "1/27/2024",
    "created_by": "Mimi Holdworth",
    "updated_date": "5/1/2024",
    "updated_by": "Valaree Hanselmann",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 3,
    "email": "emallall2@google.com.br",
    "password": "qE7&Ykbj&Foj&8",
    "role": "ADMIN",
    "full_name": "Trula Payn",
    "gender": 1,
    "phone_number": "4179788909",
    "address": "7753 Russell Avenue",
    "created_date": "2/14/2024",
    "created_by": "Celle Mattingson",
    "updated_date": "10/17/2023",
    "updated_by": "Emyle Mallall",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 4,
    "email": "abrunnen3@aboutads.info",
    "password": "gO7*Q}I/@n@*NIk",
    "role": "ADMIN",
    "full_name": "Kira Olennikov",
    "gender": 1,
    "phone_number": "6869959951",
    "address": "93 Northfield Pass",
    "created_date": "10/27/2023",
    "created_by": "Serge Salvage",
    "updated_date": "10/18/2023",
    "updated_by": "Aprilette Brunnen",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 5,
    "email": "njune4@nbcnews.com",
    "password": "pE1=tU`q\u003C",
    "role": "ADMIN",
    "full_name": "Jerome Geertsen",
    "gender": 0,
    "phone_number": "3885853313",
    "address": "22 Corry Trail",
    "created_date": "1/30/2024",
    "created_by": "Gretchen Cubley",
    "updated_date": "12/9/2023",
    "updated_by": "Netta June",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 6,
    "email": "acortez5@shoppro.jp",
    "password": "uL9(\u003CwlS}g8jw",
    "role": "ADMIN",
    "full_name": "Vlad Garfirth",
    "gender": 0,
    "phone_number": "6841422405",
    "address": "0622 Division Terrace",
    "created_date": "4/16/2024",
    "created_by": "Mandi MacFadzan",
    "updated_date": "11/17/2023",
    "updated_by": "Aridatha Cortez",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 7,
    "email": "atrathan6@ehow.com",
    "password": "kL5\u003E'm0ow~C",
    "role": "ADMIN",
    "full_name": "Maryjane Lawther",
    "gender": 1,
    "phone_number": "6839514700",
    "address": "8 Morningstar Circle",
    "created_date": "6/29/2023",
    "created_by": "Fay Larwell",
    "updated_date": "5/11/2024",
    "updated_by": "Alta Trathan",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 8,
    "email": "jlaingmaid7@hexun.com",
    "password": "sT3$vyRpF",
    "role": "ADMIN",
    "full_name": "Dare Grimmer",
    "gender": 0,
    "phone_number": "5326654258",
    "address": "2 Green Ridge Court",
    "created_date": "8/9/2023",
    "created_by": "Alysia Ovett",
    "updated_date": "10/22/2023",
    "updated_by": "Jillayne Laingmaid",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 9,
    "email": "aashborne8@mediafire.com",
    "password": "jJ9%tF_cu?!,7od|",
    "role": "ADMIN",
    "full_name": "Caleb Potzold",
    "gender": 1,
    "phone_number": "4459847704",
    "address": "2 Twin Pines Court",
    "created_date": "1/26/2024",
    "created_by": "Meredeth Mokes",
    "updated_date": "12/28/2023",
    "updated_by": "Andres Ashborne",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 10,
    "email": "lsneezum9@hibu.com",
    "password": "pG0\"$'e5kw",
    "role": "ADMIN",
    "full_name": "Lillian Peel",
    "gender": 1,
    "phone_number": "7299350235",
    "address": "029 Hoffman Lane",
    "created_date": "2/9/2024",
    "created_by": "Yalonda Linstead",
    "updated_date": "3/5/2024",
    "updated_by": "Leanora Sneezum",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 11,
    "email": "hattwoulla@ow.ly",
    "password": "cK3(WE/v`",
    "role": "ADMIN",
    "full_name": "Nike Trime",
    "gender": 0,
    "phone_number": "7556034376",
    "address": "47 Spaight Avenue",
    "created_date": "4/30/2023",
    "created_by": "Jannel Lowbridge",
    "updated_date": "10/26/2023",
    "updated_by": "Heinrick Attwoull",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 12,
    "email": "fkieferb@phpbb.com",
    "password": "bS0&\"SX*Wl",
    "role": "ADMIN",
    "full_name": "Dill Pimme",
    "gender": 0,
    "phone_number": "1306468748",
    "address": "4 Killdeer Park",
    "created_date": "10/31/2023",
    "created_by": "Rorke Mulqueen",
    "updated_date": "3/14/2024",
    "updated_by": "Felecia Kiefer",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 13,
    "email": "dmakiverc@phoca.cz",
    "password": "wS8/XqtJBT#1",
    "role": "USER",
    "full_name": "Dulci Gelland",
    "gender": 1,
    "phone_number": "3262367417",
    "address": "81831 4th Way",
    "created_date": "8/7/2023",
    "created_by": "Amelia Toynbee",
    "updated_date": "2/18/2024",
    "updated_by": "Dody Makiver",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 14,
    "email": "aadrianod@fastcompany.com",
    "password": "eE7(XfDc,K+l\u003C5",
    "role": "USER",
    "full_name": "Baillie Twigge",
    "gender": 0,
    "phone_number": "3523164329",
    "address": "687 Veith Hill",
    "created_date": "4/17/2023",
    "created_by": "Jephthah Barrows",
    "updated_date": "4/10/2024",
    "updated_by": "Alexio Adriano",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 15,
    "email": "bgrewere@bandcamp.com",
    "password": "cA6*Z2sjtt",
    "role": "USER",
    "full_name": "Cayla Yashin",
    "gender": 0,
    "phone_number": "6554973011",
    "address": "414 Forest Dale Pass",
    "created_date": "2/20/2024",
    "created_by": "Angelique Lamberts",
    "updated_date": "2/6/2024",
    "updated_by": "Berny Grewer",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 16,
    "email": "lcolthurstf@jimdo.com",
    "password": "jW6&*(heH51=$x",
    "role": "USER",
    "full_name": "Sianna Paireman",
    "gender": 0,
    "phone_number": "4866022844",
    "address": "09 Kipling Plaza",
    "created_date": "6/15/2023",
    "created_by": "Elton Twizell",
    "updated_date": "1/23/2024",
    "updated_by": "Lynnette Colthurst",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 17,
    "email": "chapkeg@census.gov",
    "password": "bR9{`U03QGR\\",
    "role": "USER",
    "full_name": "Konstance Normandale",
    "gender": 0,
    "phone_number": "6173752299",
    "address": "2119 Sachs Park",
    "created_date": "3/12/2024",
    "created_by": "Sigfried Jefferd",
    "updated_date": "2/16/2024",
    "updated_by": "Car Hapke",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 18,
    "email": "ihassallh@rakuten.co.jp",
    "password": "xN8_)%AR\u003EY48",
    "role": "USER",
    "full_name": "Nanni Jeannenet",
    "gender": 0,
    "phone_number": "9279755437",
    "address": "07 Londonderry Hill",
    "created_date": "3/24/2024",
    "created_by": "Mayne Banghe",
    "updated_date": "1/17/2024",
    "updated_by": "Isabelita Hassall",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 19,
    "email": "clivocki@cdc.gov",
    "password": "gR1.utj%q$8?",
    "role": "USER",
    "full_name": "Misty Sommer",
    "gender": 1,
    "phone_number": "6353862013",
    "address": "267 Lakeland Alley",
    "created_date": "1/2/2024",
    "created_by": "Valery Dillingham",
    "updated_date": "10/20/2023",
    "updated_by": "Christabella Livock",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 20,
    "email": "jduforej@europa.eu",
    "password": "gY9'|R\"1~t",
    "role": "USER",
    "full_name": "Ernest Haugen",
    "gender": 1,
    "phone_number": "6914367928",
    "address": "3 Mandrake Street",
    "created_date": "11/22/2023",
    "created_by": "Lynnette Issit",
    "updated_date": "4/10/2024",
    "updated_by": "Jamill Dufore",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 21,
    "email": "ebushbyk@soundcloud.com",
    "password": "dC2/cyXn6+E|",
    "role": "USER",
    "full_name": "Joseito Partner",
    "gender": 0,
    "phone_number": "1403447692",
    "address": "53 Blaine Plaza",
    "created_date": "9/5/2023",
    "created_by": "Sly Regardsoe",
    "updated_date": "6/4/2024",
    "updated_by": "Essie Bushby",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 22,
    "email": "gjacklingl@apple.com",
    "password": "dP2)VJ+V$",
    "role": "USER",
    "full_name": "Marci Betchley",
    "gender": 1,
    "phone_number": "3723900197",
    "address": "63 Eggendart Plaza",
    "created_date": "1/25/2024",
    "created_by": "Panchito Mardling",
    "updated_date": "3/13/2024",
    "updated_by": "Gan Jackling",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 23,
    "email": "bcouldwellm@blog.com",
    "password": "yK3@Nx.PCuubE",
    "role": "USER",
    "full_name": "Tristan Sultana",
    "gender": 1,
    "phone_number": "5731606186",
    "address": "735 Caliangt Point",
    "created_date": "8/16/2023",
    "created_by": "Carilyn Mugglestone",
    "updated_date": "2/15/2024",
    "updated_by": "Bear Couldwell",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 24,
    "email": "bpablon@europa.eu",
    "password": "iL3_'i!8\\",
    "role": "USER",
    "full_name": "Virge Steynor",
    "gender": 0,
    "phone_number": "6474001129",
    "address": "016 Eliot Drive",
    "created_date": "11/19/2023",
    "created_by": "Gertrude Ranvoise",
    "updated_date": "11/28/2023",
    "updated_by": "Berni Pablo",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 25,
    "email": "srzehorzo@merriamwebster.com",
    "password": "bJ2{cXG/Gu)p",
    "role": "USER",
    "full_name": "Tawsha Kolak",
    "gender": 1,
    "phone_number": "8727892392",
    "address": "629 Sunnyside Trail",
    "created_date": "8/19/2023",
    "created_by": "Phedra Amyes",
    "updated_date": "2/9/2024",
    "updated_by": "Sibylla Rzehorz",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 26,
    "email": "amcconachiep@eventbrite.com",
    "password": "aH7#d6~Pix{",
    "role": "ADMIN",
    "full_name": "Elvera Teall",
    "gender": 0,
    "phone_number": "1609331211",
    "address": "637 Anzinger Way",
    "created_date": "6/3/2023",
    "created_by": "Russell Korbmaker",
    "updated_date": "2/11/2024",
    "updated_by": "Audrey McConachie",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 27,
    "email": "cjervoiseq@rambler.ru",
    "password": "eJ8+V@25siyIyf",
    "role": "ADMIN",
    "full_name": "Patrizia Giddons",
    "gender": 1,
    "phone_number": "3131006548",
    "address": "362 Jenna Hill",
    "created_date": "8/31/2023",
    "created_by": "Franz Millbank",
    "updated_date": "11/21/2023",
    "updated_by": "Cindra Jervoise",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 28,
    "email": "cmckeurtonr@google.com.hk",
    "password": "qS7\u003E7y2wyX",
    "role": "ADMIN",
    "full_name": "Ernestine Danev",
    "gender": 1,
    "phone_number": "4079530504",
    "address": "820 Continental Hill",
    "created_date": "1/30/2024",
    "created_by": "Arlee Gotmann",
    "updated_date": "12/20/2023",
    "updated_by": "Chilton McKeurton",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 29,
    "email": "smerwedes@example.com",
    "password": "zP2~3D\"G#Zvg{be6",
    "role": "ADMIN",
    "full_name": "Ophelia Haythorne",
    "gender": 1,
    "phone_number": "3965119488",
    "address": "46170 Eastlawn Drive",
    "created_date": "8/3/2023",
    "created_by": "Alic Chicotti",
    "updated_date": "2/10/2024",
    "updated_by": "Sioux Merwede",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 30,
    "email": "bduffieldt@topsy.com",
    "password": "gJ0.m'rNeum\u003CTP@d",
    "role": "ADMIN",
    "full_name": "Marylin Valiant",
    "gender": 0,
    "phone_number": "2286628426",
    "address": "875 Ryan Way",
    "created_date": "7/22/2023",
    "created_by": "Karoly Pymer",
    "updated_date": "3/2/2024",
    "updated_by": "Bale Duffield",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 31,
    "email": "mmccarneyu@delicious.com",
    "password": "wY7~$u=O",
    "role": "ADMIN",
    "full_name": "Rudolph Grossier",
    "gender": 1,
    "phone_number": "3201381414",
    "address": "68 Pearson Park",
    "created_date": "8/2/2023",
    "created_by": "Camel Montacute",
    "updated_date": "4/1/2024",
    "updated_by": "Manya McCarney",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 32,
    "email": "lmielnikv@webnode.com",
    "password": "pJ7\u003E0#\\~J",
    "role": "EMPLOYEE",
    "full_name": "Jamal Londer",
    "gender": 1,
    "phone_number": "8913177971",
    "address": "56794 Johnson Terrace",
    "created_date": "5/19/2024",
    "created_by": "Alphard Boland",
    "updated_date": "10/14/2023",
    "updated_by": "Luisa Mielnik",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 33,
    "email": "nstutherw@google.es",
    "password": "jA0\\u\"@\u003Cvy",
    "role": "EMPLOYEE",
    "full_name": "Filia Patrick",
    "gender": 0,
    "phone_number": "6325193168",
    "address": "00 Independence Parkway",
    "created_date": "4/8/2023",
    "created_by": "Robinett Abela",
    "updated_date": "3/25/2024",
    "updated_by": "Natasha Stuther",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 34,
    "email": "edonovinx@liveinternet.ru",
    "password": "wX5$ujpi1",
    "role": "EMPLOYEE",
    "full_name": "Rhona Lindeberg",
    "gender": 0,
    "phone_number": "9549316300",
    "address": "6064 Buell Park",
    "created_date": "8/30/2023",
    "created_by": "Alli Littlekit",
    "updated_date": "11/27/2023",
    "updated_by": "Evan Donovin",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 35,
    "email": "draity@marketwatch.com",
    "password": "zC1&+r`{ZvsS2",
    "role": "EMPLOYEE",
    "full_name": "Forester Crookshank",
    "gender": 1,
    "phone_number": "1575658140",
    "address": "409 Shasta Street",
    "created_date": "4/15/2024",
    "created_by": "Frankie Forte",
    "updated_date": "11/17/2023",
    "updated_by": "Dory Rait",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 36,
    "email": "lmioniz@craigslist.org",
    "password": "xO2(NTfO",
    "role": "EMPLOYEE",
    "full_name": "Sidonnie Oven",
    "gender": 0,
    "phone_number": "4344783760",
    "address": "449 Ronald Regan Drive",
    "created_date": "1/12/2024",
    "created_by": "Luciana Tuttle",
    "updated_date": "6/13/2024",
    "updated_by": "Law Mioni",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 37,
    "email": "ctrappe10@pbs.org",
    "password": "aH6%bZt5it~",
    "role": "EMPLOYEE",
    "full_name": "Deloria Scolli",
    "gender": 0,
    "phone_number": "6561388879",
    "address": "54601 Mccormick Circle",
    "created_date": "5/21/2024",
    "created_by": "Griffie Conring",
    "updated_date": "11/10/2023",
    "updated_by": "Carlo Trappe",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 38,
    "email": "wdehn11@geocities.jp",
    "password": "uJ7!VN/MVc",
    "role": "EMPLOYEE",
    "full_name": "Lay Sanford",
    "gender": 1,
    "phone_number": "4712264548",
    "address": "302 Fuller Center",
    "created_date": "9/18/2023",
    "created_by": "Sascha Perone",
    "updated_date": "11/26/2023",
    "updated_by": "Wallis Dehn",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 39,
    "email": "fbradock12@hexun.com",
    "password": "lW1=$cz@yGWF,",
    "role": "EMPLOYEE",
    "full_name": "Teri Hinstock",
    "gender": 0,
    "phone_number": "2123970117",
    "address": "43769 Thackeray Hill",
    "created_date": "4/5/2024",
    "created_by": "Philippa Feehily",
    "updated_date": "3/24/2024",
    "updated_by": "Franciska Bradock",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 40,
    "email": "ecollinette13@gizmodo.com",
    "password": "qG4\"@1+D2ZB&wt",
    "role": "EMPLOYEE",
    "full_name": "Sim Spearman",
    "gender": 1,
    "phone_number": "3759968964",
    "address": "76 Loeprich Park",
    "created_date": "7/25/2023",
    "created_by": "Ewan Mitchiner",
    "updated_date": "3/8/2024",
    "updated_by": "Emily Collinette",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 41,
    "email": "kmaycey14@istockphoto.com",
    "password": "tW2}S+e?(",
    "role": "EMPLOYEE",
    "full_name": "Lisbeth Engelbrecht",
    "gender": 1,
    "phone_number": "1203326473",
    "address": "9320 Eliot Way",
    "created_date": "9/20/2023",
    "created_by": "Derrick Jandel",
    "updated_date": "6/9/2024",
    "updated_by": "Karoly Maycey",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 42,
    "email": "zcarus15@washingtonpost.com",
    "password": "vC8!VJDO}z9",
    "role": "EMPLOYEE",
    "full_name": "Joela Service",
    "gender": 1,
    "phone_number": "9153289391",
    "address": "755 Warner Way",
    "created_date": "3/21/2024",
    "created_by": "Reilly Giddons",
    "updated_date": "4/8/2024",
    "updated_by": "Zenia Carus",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 43,
    "email": "ralam16@usatoday.com",
    "password": "eQ2&#f48)(F\"o|e",
    "role": "EMPLOYEE",
    "full_name": "Giovanna Weekland",
    "gender": 1,
    "phone_number": "1777340935",
    "address": "1174 Debs Avenue",
    "created_date": "6/2/2023",
    "created_by": "Celesta Roake",
    "updated_date": "2/28/2024",
    "updated_by": "Robbin Alam",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 44,
    "email": "ithinn17@macromedia.com",
    "password": "pJ0\\2_(}{",
    "role": "EMPLOYEE",
    "full_name": "Karlen Veronique",
    "gender": 0,
    "phone_number": "6016421936",
    "address": "58463 Luster Road",
    "created_date": "4/4/2023",
    "created_by": "Wrennie Shemmin",
    "updated_date": "3/25/2024",
    "updated_by": "Innis Thinn",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 45,
    "email": "mketton18@bandcamp.com",
    "password": "yK4\u003C@hp(P/IW",
    "role": "ADMIN",
    "full_name": "Vanda Simcock",
    "gender": 1,
    "phone_number": "4054901543",
    "address": "88426 Harper Parkway",
    "created_date": "7/28/2023",
    "created_by": "Harp Polglase",
    "updated_date": "10/26/2023",
    "updated_by": "Marja Ketton",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 46,
    "email": "bpetters19@devhub.com",
    "password": "zS8%mKw)D2?",
    "role": "ADMIN",
    "full_name": "Brnaby Gowler",
    "gender": 1,
    "phone_number": "9138005822",
    "address": "1553 John Wall Place",
    "created_date": "7/15/2023",
    "created_by": "Timmi MacKaile",
    "updated_date": "6/5/2024",
    "updated_by": "Brandais Petters",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 47,
    "email": "afalla1a@ibm.com",
    "password": "pI9'8\\e3+8t!",
    "role": "ADMIN",
    "full_name": "Selby Banck",
    "gender": 1,
    "phone_number": "8236780089",
    "address": "00885 Bluejay Alley",
    "created_date": "5/15/2023",
    "created_by": "Westley Rops",
    "updated_date": "11/3/2023",
    "updated_by": "Alexandra Falla",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 48,
    "email": "ajoyson1b@slideshare.net",
    "password": "wJ9?t?\",fR",
    "role": "ADMIN",
    "full_name": "Angelo Maltby",
    "gender": 0,
    "phone_number": "1248613412",
    "address": "200 Vera Circle",
    "created_date": "2/24/2024",
    "created_by": "Morganne Brockie",
    "updated_date": "11/15/2023",
    "updated_by": "Althea Joyson",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 49,
    "email": "evaines1c@alibaba.com",
    "password": "gZ3(J)Hp}K5E",
    "role": "ADMIN",
    "full_name": "Maximilien Fardo",
    "gender": 1,
    "phone_number": "3066631809",
    "address": "6 Vera Park",
    "created_date": "7/16/2023",
    "created_by": "Aylmar McCathie",
    "updated_date": "2/6/2024",
    "updated_by": "Erin Vaines",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  },
  {
    "id": 50,
    "email": "mcrinidge1d@usatoday.com",
    "password": "lC1=\u003CYK)2O!\u003E+b&o",
    "role": "ADMIN",
    "full_name": "Dylan Aslie",
    "gender": 0,
    "phone_number": "2568954200",
    "address": "9111 Drewry Road",
    "created_date": "2/8/2024",
    "created_by": "Cordula Junkinson",
    "updated_date": "2/9/2024",
    "updated_by": "Madelena Crinidge",
    "imageUrl": "/assets/images/avatars/avatar_25.jpg"
  }
]