version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Quandz@@2083
    networks:
      - quanndb_network

  mysql:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Quandz@@2083
    networks:
      - quanndb_network

  lowland-backend:
    image: lowland/backend:latest
    build:
      context: ./back-end/LowLand
    restart: always
    ports:
      - 2818:2818
    environment:
      #APP
      - APP_SECRET_KEY=
      - APP_ORIGIN_CLIENT=http://localhost:5173
      - APP_ORIGIN_ADMIN=http://localhost:5174
      #MySQL
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/lowland
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Quandz@@2083
      #Mongo
      - SPRING_DATA_MONGO_DATABASE=lowland
      - SPRING_DATA_MONGO_URI=mongodb://root:Quandz%40%402083@mongo:27017/
      #Cloudinary
      - CLOUD_NAME=
      - CLOUD_API_KEY=
      - CLOUD_API_SECRET=
      #PayOS
      - PAYOS_CLIENT_ID=
      - PAYOS_CLIENT_SECRET=
      - PAYOS_CHECKSUM_KEY=
      #Google
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=

    depends_on:
      - mongo
      - mysql
    networks:
      - quanndb_network

  lowland-admin:
    image: lowland/admin:latest
    build:
      context: ./front-end/Admin
      args:
        VITE_SERVER_BASE_URL: http://localhost:2818/api/v1.0.0
        VITE_CLIENT: http://localhost:5173
    restart: always
    ports:
      - 5174:80
    environment:
      - VITE_SERVER_BASE_URL=http://localhost:2818/api/v1.0.0
      - VITE_CLIENT=http://localhost:5173
    depends_on:
      - lowland-backend
    networks:
      - quanndb_network

  lowland-client:
    image: lowland/client:latest
    build:
      context: ./front-end/Client
      args:
        VITE_SERVER_BASE_URL: http://localhost:2818/api/v1.0.0
        VITE_CLIENT_ID:
    restart: always
    ports:
      - 5173:80
    environment:
      - VITE_SERVER_BASE_URL=http://localhost:2818/api/v1.0.0
      - VITE_CLIENT_ID=
    depends_on:
      - lowland-backend
    networks:
      - quanndb_network

networks:
  quanndb_network:
    driver: bridge
