version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Quandz@@2083
    networks:
      - quanndb_network

  mysql:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Quandz@@2083
    networks:
      - quanndb_network

  lowland-backend:
    image: lowland/backend:latest
    build: 
      context: ./back-end/LowLand
    restart: always
    ports:
      - 2818:2818
    environment:
      #Database
      #MySQL
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/lowland
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Quandz@@2083
      #Mongo
      - SPRING_DATA_MONGO_DATABASE=lowland
      - SPRING_DATA_MONGO_URL=mongodb://root:Quandz%40%402083@mongo:27017

    depends_on:
      - mongo
      - mysql
    networks:
      - quanndb_network

  lowland-admin:
    image: lowland/admin:latest
    build: 
      context: ./front-end/Admin
    restart: always
    ports: 
      - 5173:80
    depends_on:
      - lowland-backend
    networks:
      - quanndb_network
  
  lowland-client:
    image: lowland/client:latest
    build: 
      context: ./front-end/Client
    restart: always
    ports: 
      - 5174:80
    depends_on:
      - lowland-backend
    networks:
      - quanndb_network

networks:
  quanndb_network:
    driver: bridge