use java_lowland;
-- MySQL Script generated by MySQL Workbench
-- Wed May 29 13:41:13 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema java_lowland
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema java_lowland
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `java_lowland` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `java_lowland` ;

-- -----------------------------------------------------
-- Table `java_lowland`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`account` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`account` (
  `accountID` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` TEXT NULL DEFAULT NULL,
  `role` VARCHAR(45) NULL DEFAULT NULL,
  `full_name` VARCHAR(250) NULL DEFAULT NULL,
  `gender` INT NULL DEFAULT NULL COMMENT '0: NỮ; 1: Nam; 2: Khác',
  `phone_number` VARCHAR(250) NULL DEFAULT NULL,
  `address` TEXT NULL DEFAULT NULL,
  `created_date` DATETIME NULL DEFAULT NULL,
  `created_by` VARCHAR(250) NULL DEFAULT NULL,
  `updated_date` DATETIME NULL DEFAULT NULL,
  `updated_by` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`accountID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`accountimage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`accountimage` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`accountimage` (
  `account_image_ID` INT NOT NULL AUTO_INCREMENT,
  `account_ID` INT NULL DEFAULT NULL,
  `image_ID` INT NULL DEFAULT NULL,
  `is_avatar` BIT(1) NULL DEFAULT NULL,
  `created_date` DATETIME NULL DEFAULT NULL,
  `created_by` VARCHAR(250) NULL DEFAULT NULL,
  `updated_date` DATETIME NULL DEFAULT NULL,
  `updated_by` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`accountImageId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`blog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`blog` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`blog` (
  `blogId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `content` VARCHAR(45) NULL DEFAULT NULL,
  `imageUrl` VARCHAR(45) NULL DEFAULT NULL,
  `createdDate` DATETIME NULL DEFAULT NULL,
  `createdBy` VARCHAR(250) NULL DEFAULT NULL,
  `updatedDate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`blogId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`bloglike`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`bloglike` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`bloglike` (
  `blogLikeId` INT NOT NULL AUTO_INCREMENT,
  `blogId` INT NULL DEFAULT NULL,
  `accountId` INT NULL DEFAULT NULL,
  `createdDate` DATETIME NULL DEFAULT NULL,
  `createdBy` VARCHAR(250) NULL DEFAULT NULL,
  `updatedDate` DATETIME NULL DEFAULT NULL,
  `updatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`blogLikeId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`comment` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`comment` (
  `commentId` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL DEFAULT NULL,
  `blogId` INT NULL DEFAULT NULL,
  `accountId` INT NULL DEFAULT NULL,
  `createdDate` DATETIME NULL DEFAULT NULL,
  `createdBy` VARCHAR(250) NULL DEFAULT NULL,
  `updatedDate` DATETIME NULL DEFAULT NULL,
  `updatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`commentId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`commentlike`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`commentlike` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`commentlike` (
  `commentLikeId` INT NOT NULL AUTO_INCREMENT,
  `accountId` INT NULL DEFAULT NULL,
  `commentId` INT NULL DEFAULT NULL,
  `isLike` BIT(1) NULL DEFAULT NULL,
  `createdDate` DATETIME NULL DEFAULT NULL,
  `createdBy` VARCHAR(250) NULL DEFAULT NULL,
  `updatedDate` DATETIME NULL DEFAULT NULL,
  `updatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`commentLikeId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`image` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`image` (
  `imageId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `imageUrl` VARCHAR(255) NULL DEFAULT NULL,
  `cloudId` INT NULL DEFAULT NULL,
  `imageName` VARCHAR(255) NULL DEFAULT NULL,
  `createdDate` DATETIME NULL DEFAULT NULL,
  `createdBy` VARCHAR(250) NULL DEFAULT NULL,
  `updatedDate` DATETIME NULL DEFAULT NULL,
  `updatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`imageId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`importstock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`importstock` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`importstock` (
  `importStockId` INT NOT NULL AUTO_INCREMENT,
  `supplierCode` VARCHAR(45) NULL DEFAULT NULL,
  `supplierName` VARCHAR(250) NULL DEFAULT NULL,
  `description` VARCHAR(250) NULL DEFAULT NULL,
  `importDate` VARCHAR(250) NULL DEFAULT NULL,
  `createdDate` DATETIME NULL DEFAULT NULL,
  `createdBy` VARCHAR(250) NULL DEFAULT NULL,
  `updatedDate` DATETIME NULL DEFAULT NULL,
  `updatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`importStockId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`importstockdetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`importstockdetails` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`importstockdetails` (
  `detailsId` INT NOT NULL AUTO_INCREMENT,
  `importStockId` INT NULL DEFAULT NULL,
  `materialId` INT NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `price` DECIMAL(18,2) NULL DEFAULT NULL,
  `createdDate` DATETIME NULL DEFAULT NULL,
  `createdBy` VARCHAR(250) NULL DEFAULT NULL,
  `updatedDate` DATETIME NULL DEFAULT NULL,
  `updatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`detailsId`),
  UNIQUE INDEX `detailsId_UNIQUE` (`detailsId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`material` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`material` (
  `materialId` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `minQuantity` INT NULL DEFAULT NULL,
  `materialGroupId` INT NULL DEFAULT NULL,
  `unitId` INT NULL DEFAULT NULL,
  `createdDate` DATETIME NULL DEFAULT NULL,
  `createdBy` VARCHAR(250) NULL DEFAULT NULL,
  `updatedDate` DATETIME NULL DEFAULT NULL,
  `updatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`materialId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`materialgroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`materialgroup` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`materialgroup` (
  `materialGroupId` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(250) NULL DEFAULT NULL,
  `createdDate` DATETIME NULL DEFAULT NULL,
  `createdBy` VARCHAR(250) NULL DEFAULT NULL,
  `updatedDate` DATETIME NULL DEFAULT NULL,
  `updatedBy` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`materialGroupId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`order` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`order` (
  `orderId` INT NOT NULL AUTO_INCREMENT,
  `customerName` VARCHAR(255) NOT NULL,
  `phoneNumber` VARCHAR(250) NOT NULL,
  `address` TEXT NOT NULL,
  `status` INT NOT NULL COMMENT '1: Đang chờ xác nhận đơn hàng\\n2: Đơn hàng đã được giao\\n3: Hủy đơn hàng thành công',
  `accountId` INT NOT NULL,
  `createDate` DATETIME NOT NULL,
  `createdBy` VARCHAR(250) NOT NULL,
  `updatedDate` DATETIME NULL DEFAULT NULL,
  `updatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`orderId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`orderdetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`orderdetails` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`orderdetails` (
  `orderDetailsId` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NULL DEFAULT NULL,
  `totalMoney` DECIMAL(18,2) NULL DEFAULT NULL,
  `orderId` INT NULL DEFAULT NULL,
  `productDetailsId` INT NULL DEFAULT NULL,
  `createdDate` DATETIME NULL DEFAULT NULL,
  `createdBy` VARCHAR(250) NULL DEFAULT NULL,
  `updatedDate` DATETIME NULL DEFAULT NULL,
  `updatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`orderDetailsId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`product` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`product` (
  `productId` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(250) NULL DEFAULT NULL,
  `isActive` BIT(1) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `productTypeId` INT NULL DEFAULT NULL,
  `createdDate` DATETIME NULL DEFAULT NULL,
  `createdBy` VARCHAR(250) NULL DEFAULT NULL,
  `updatedDate` DATETIME NULL DEFAULT NULL,
  `updatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`productId`),
  UNIQUE INDEX `productId_UNIQUE` (`productId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '																	';


-- -----------------------------------------------------
-- Table `java_lowland`.`productdetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`productdetails` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`productdetails` (
  `productDetailsId` INT NOT NULL AUTO_INCREMENT,
  `productId` INT NULL DEFAULT NULL,
  `productSizeId` INT NULL DEFAULT NULL,
  `price` DECIMAL(18,2) NULL DEFAULT NULL,
  `createdDate` DATETIME NULL DEFAULT NULL,
  `createdBy` VARCHAR(250) NULL DEFAULT NULL,
  `updatedDate` DATETIME NULL DEFAULT NULL,
  `updatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`productDetailsId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`productimage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`productimage` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`productimage` (
  `productImageId` INT NOT NULL AUTO_INCREMENT,
  `imageId` INT NOT NULL,
  `productId` INT NOT NULL,
  `createdDate` DATETIME NULL DEFAULT NULL,
  `createdBy` VARCHAR(250) NULL DEFAULT NULL,
  `updatedDate` DATETIME NULL DEFAULT NULL,
  `updatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`productImageId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`productrecipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`productrecipe` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`productrecipe` (
  `productRecipeId` INT NOT NULL AUTO_INCREMENT,
  `productId` INT NULL DEFAULT NULL,
  `materialId` INT NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `createdDate` DATETIME NULL DEFAULT NULL,
  `createdBy` VARCHAR(250) NULL DEFAULT NULL,
  `updatedDate` DATETIME NULL DEFAULT NULL,
  `updatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`productRecipeId`),
  UNIQUE INDEX `productRecipeId_UNIQUE` (`productRecipeId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`productsize`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`productsize` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`productsize` (
  `productSizeId` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(250) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `createdDate` DATETIME NULL DEFAULT NULL,
  `updatedDate` DATETIME NULL DEFAULT NULL,
  `updatedBy` VARCHAR(250) NULL DEFAULT NULL,
  `createdBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`productSizeId`),
  UNIQUE INDEX `productSizeId_UNIQUE` (`productSizeId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`producttype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`producttype` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`producttype` (
  `productTypeId` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(250) NULL DEFAULT NULL,
  `productId` INT NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `createdDate` DATETIME NULL DEFAULT NULL,
  `createdBy` VARCHAR(250) NULL DEFAULT NULL,
  `updatedDate` DATETIME NULL DEFAULT NULL,
  `updatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`productTypeId`),
  UNIQUE INDEX `productTypeId_UNIQUE` (`productTypeId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`unit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`unit` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`unit` (
  `unitId` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `unitTypeId` VARCHAR(45) NULL DEFAULT NULL,
  `materialId` INT NULL DEFAULT NULL,
  `createdDate` DATETIME NULL DEFAULT NULL,
  `createdBy` VARCHAR(250) NULL DEFAULT NULL,
  `updatedDate` DATETIME NULL DEFAULT NULL,
  `updatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`unitId`),
  UNIQUE INDEX `unitId_UNIQUE` (`unitId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
