use lowland;
-- MySQL Script generated by MySQL Workbench
-- Wed May 29 13:41:13 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema java_lowland
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema java_lowland
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `java_lowland` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `java_lowland` ;

-- -----------------------------------------------------
-- Table `java_lowland`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`account` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`account` (
  `AccountId` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(255) NULL DEFAULT NULL,
  `Password` TEXT NULL DEFAULT NULL,
  `Role` VARCHAR(45) NULL DEFAULT NULL,
  `FullName` VARCHAR(250) NULL DEFAULT NULL,
  `Gender` INT NULL DEFAULT NULL COMMENT '0: NỮ; 1: Nam; 2: Khác',
  `PhoneNumber` VARCHAR(250) NULL DEFAULT NULL,
  `Address` TEXT NULL DEFAULT NULL,
  `CreatedDate` DATETIME NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(250) NULL DEFAULT NULL,
  `UpdatedDate` DATETIME NULL DEFAULT NULL,
  `UpdatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`AccountId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`accountimage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`accountimage` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`accountimage` (
  `AccountImageId` INT NOT NULL AUTO_INCREMENT,
  `AccountId` INT NULL DEFAULT NULL,
  `ImageId` INT NULL DEFAULT NULL,
  `IsAvatar` BIT(1) NULL DEFAULT NULL,
  `CreatedDate` DATETIME NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(250) NULL DEFAULT NULL,
  `UpdatedDate` DATETIME NULL DEFAULT NULL,
  `UpdatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`AccountImageId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`blog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`blog` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`blog` (
  `BlogId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NULL DEFAULT NULL,
  `Content` VARCHAR(45) NULL DEFAULT NULL,
  `ImageUrl` VARCHAR(45) NULL DEFAULT NULL,
  `CreatedDate` DATETIME NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(250) NULL DEFAULT NULL,
  `UpdatedDate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`BlogId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`bloglike`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`bloglike` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`bloglike` (
  `BlogLikeId` INT NOT NULL AUTO_INCREMENT,
  `BlogId` INT NULL DEFAULT NULL,
  `AccountId` INT NULL DEFAULT NULL,
  `CreatedDate` DATETIME NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(250) NULL DEFAULT NULL,
  `UpdatedDate` DATETIME NULL DEFAULT NULL,
  `UpdatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`BlogLikeId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`comment` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`comment` (
  `CommentId` INT NOT NULL AUTO_INCREMENT,
  `Content` TEXT NULL DEFAULT NULL,
  `BlogId` INT NULL DEFAULT NULL,
  `AccountId` INT NULL DEFAULT NULL,
  `CreatedDate` DATETIME NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(250) NULL DEFAULT NULL,
  `UpdatedDate` DATETIME NULL DEFAULT NULL,
  `UpdatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`CommentId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`commentlike`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`commentlike` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`commentlike` (
  `CommentLikeId` INT NOT NULL AUTO_INCREMENT,
  `AccountId` INT NULL DEFAULT NULL,
  `CommentId` INT NULL DEFAULT NULL,
  `IsLike` BIT(1) NULL DEFAULT NULL,
  `CreatedDate` DATETIME NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(250) NULL DEFAULT NULL,
  `UpdatedDate` DATETIME NULL DEFAULT NULL,
  `UpdatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`CommentLikeId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`image` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`image` (
  `ImageId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ImageUrl` VARCHAR(255) NULL DEFAULT NULL,
  `CloudId` INT NULL DEFAULT NULL,
  `ImageName` VARCHAR(255) NULL DEFAULT NULL,
  `CreatedDate` DATETIME NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(250) NULL DEFAULT NULL,
  `UpdatedDate` DATETIME NULL DEFAULT NULL,
  `UpdatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`ImageId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`importstock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`importstock` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`importstock` (
  `ImportStockId` INT NOT NULL AUTO_INCREMENT,
  `SupplierCode` VARCHAR(45) NULL DEFAULT NULL,
  `SupplierName` VARCHAR(250) NULL DEFAULT NULL,
  `Description` VARCHAR(250) NULL DEFAULT NULL,
  `ImportDate` VARCHAR(250) NULL DEFAULT NULL,
  `CreatedDate` DATETIME NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(250) NULL DEFAULT NULL,
  `UpdatedDate` DATETIME NULL DEFAULT NULL,
  `UpdatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`ImportStockId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`importstockdetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`importstockdetails` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`importstockdetails` (
  `DetailsId` INT NOT NULL AUTO_INCREMENT,
  `ImportStockId` INT NULL DEFAULT NULL,
  `MaterialId` INT NULL DEFAULT NULL,
  `Quantity` INT NULL DEFAULT NULL,
  `Price` DECIMAL(18,2) NULL DEFAULT NULL,
  `CreatedDate` DATETIME NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(250) NULL DEFAULT NULL,
  `UpdatedDate` DATETIME NULL DEFAULT NULL,
  `UpdatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`DetailsId`),
  UNIQUE INDEX `DetailsId_UNIQUE` (`DetailsId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`material` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`material` (
  `MaterialId` INT NOT NULL AUTO_INCREMENT,
  `Code` VARCHAR(45) NULL DEFAULT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Quantity` INT NULL DEFAULT NULL,
  `MinQuantity` INT NULL DEFAULT NULL,
  `MaterialGroupId` INT NULL DEFAULT NULL,
  `UnitId` INT NULL DEFAULT NULL,
  `CreatedDate` DATETIME NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(250) NULL DEFAULT NULL,
  `UpdatedDate` DATETIME NULL DEFAULT NULL,
  `UpdatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`MaterialId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`materialgroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`materialgroup` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`materialgroup` (
  `MaterialGroupId` INT NOT NULL AUTO_INCREMENT,
  `Code` VARCHAR(45) NULL DEFAULT NULL,
  `Name` VARCHAR(250) NULL DEFAULT NULL,
  `CreatedDate` DATETIME NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(250) NULL DEFAULT NULL,
  `UpdatedDate` DATETIME NULL DEFAULT NULL,
  `UpdatedBy` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`MaterialGroupId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`order` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`order` (
  `OrderId` INT NOT NULL AUTO_INCREMENT,
  `CustomerName` VARCHAR(255) NOT NULL,
  `PhoneNumber` VARCHAR(250) NOT NULL,
  `Address` TEXT NOT NULL,
  `Status` INT NOT NULL COMMENT '1: Đang chờ xác nhận đơn hàng\\n2: Đơn hàng đã được giao\\n3: Hủy đơn hàng thành công',
  `AccountId` INT NOT NULL,
  `CreateDate` DATETIME NOT NULL,
  `CreatedBy` VARCHAR(250) NOT NULL,
  `UpdatedDate` DATETIME NULL DEFAULT NULL,
  `UpdatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`OrderId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`orderdetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`orderdetails` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`orderdetails` (
  `OrderDetailsId` INT NOT NULL AUTO_INCREMENT,
  `Quantity` INT NULL DEFAULT NULL,
  `TotalMoney` DECIMAL(18,2) NULL DEFAULT NULL,
  `OrderId` INT NULL DEFAULT NULL,
  `ProductDetailsId` INT NULL DEFAULT NULL,
  `CreatedDate` DATETIME NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(250) NULL DEFAULT NULL,
  `UpdatedDate` DATETIME NULL DEFAULT NULL,
  `UpdatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`OrderDetailsId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`product` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`product` (
  `ProductId` INT NOT NULL AUTO_INCREMENT,
  `Code` VARCHAR(45) NULL DEFAULT NULL,
  `Name` VARCHAR(250) NULL DEFAULT NULL,
  `IsActive` BIT(1) NULL DEFAULT NULL,
  `Description` VARCHAR(255) NULL DEFAULT NULL,
  `ProductTypeId` INT NULL DEFAULT NULL,
  `CreatedDate` DATETIME NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(250) NULL DEFAULT NULL,
  `UpdatedDate` DATETIME NULL DEFAULT NULL,
  `UpdatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`ProductId`),
  UNIQUE INDEX `ProductId_UNIQUE` (`ProductId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '																	';


-- -----------------------------------------------------
-- Table `java_lowland`.`productdetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`productdetails` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`productdetails` (
  `ProductDetailsId` INT NOT NULL AUTO_INCREMENT,
  `ProductId` INT NULL DEFAULT NULL,
  `ProductSizeId` INT NULL DEFAULT NULL,
  `Price` DECIMAL(18,2) NULL DEFAULT NULL,
  `CreatedDate` DATETIME NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(250) NULL DEFAULT NULL,
  `UpdatedDate` DATETIME NULL DEFAULT NULL,
  `UpdatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`ProductDetailsId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`productimage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`productimage` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`productimage` (
  `ProductImageId` INT NOT NULL AUTO_INCREMENT,
  `ImageId` INT NOT NULL,
  `ProductId` INT NOT NULL,
  `CreatedDate` DATETIME NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(250) NULL DEFAULT NULL,
  `UpdatedDate` DATETIME NULL DEFAULT NULL,
  `UpdatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`ProductImageId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`productrecipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`productrecipe` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`productrecipe` (
  `ProductRecipeId` INT NOT NULL AUTO_INCREMENT,
  `ProductId` INT NULL DEFAULT NULL,
  `MaterialId` INT NULL DEFAULT NULL,
  `Quantity` INT NULL DEFAULT NULL,
  `CreatedDate` DATETIME NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(250) NULL DEFAULT NULL,
  `UpdatedDate` DATETIME NULL DEFAULT NULL,
  `UpdatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`ProductRecipeId`),
  UNIQUE INDEX `ProductRecipeId_UNIQUE` (`ProductRecipeId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`productsize`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`productsize` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`productsize` (
  `ProductSizeId` INT NOT NULL AUTO_INCREMENT,
  `Code` VARCHAR(45) NULL DEFAULT NULL,
  `Name` VARCHAR(250) NULL DEFAULT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  `CreatedDate` DATETIME NULL DEFAULT NULL,
  `UpdatedDate` DATETIME NULL DEFAULT NULL,
  `UpdatedBy` VARCHAR(250) NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`ProductSizeId`),
  UNIQUE INDEX `ProductSizeId_UNIQUE` (`ProductSizeId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`producttype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`producttype` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`producttype` (
  `ProductTypeId` INT NOT NULL AUTO_INCREMENT,
  `Code` VARCHAR(45) NULL DEFAULT NULL,
  `Name` VARCHAR(250) NULL DEFAULT NULL,
  `ProductId` INT NULL DEFAULT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  `CreatedDate` DATETIME NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(250) NULL DEFAULT NULL,
  `UpdatedDate` DATETIME NULL DEFAULT NULL,
  `UpdatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`ProductTypeId`),
  UNIQUE INDEX `ProductTypeId_UNIQUE` (`ProductTypeId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `java_lowland`.`unit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java_lowland`.`unit` ;

CREATE TABLE IF NOT EXISTS `java_lowland`.`unit` (
  `UnitId` INT NOT NULL AUTO_INCREMENT,
  `Code` VARCHAR(45) NULL DEFAULT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `UnitTypeId` VARCHAR(45) NULL DEFAULT NULL,
  `MaterialId` INT NULL DEFAULT NULL,
  `CreatedDate` DATETIME NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(250) NULL DEFAULT NULL,
  `UpdatedDate` DATETIME NULL DEFAULT NULL,
  `UpdatedBy` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`UnitId`),
  UNIQUE INDEX `UnitId_UNIQUE` (`UnitId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
